=== api-evangelist/navision/json-schema/business-central-v2-purchase-order-line-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "PurchaseOrderLine",
  "type": "object",
  "properties": {
    "@odata.etag": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "documentId": {
      "type": "string"
    },
    "sequence": {
      "type": "integer"
    },
    "itemId": {
      "type": "string"
    },
    "accountId": {
      "type": "string"
    },
    "lineType": {
      "type": "string"
    },
    "lineObjectNumber": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "description2": {
      "type": "string"
    },
    "unitOfMeasureId": {
      "type": "string"
    },
    "unitOfMeasureCode": {
      "type": "string"
    },
    "quantity": {
      "type": "number"
    },
    "directUnitCost": {
      "type": "number"
    },
    "discountAmount": {
      "type": "number"
    },
    "discountPercent": {
      "type": "number"
    },
    "discountAppliedBeforeTax": {
      "type": "boolean"
    },
    "amountExcludingTax": {
      "type": "number"
    },
    "taxCode": {
      "type": "string"
    },
    "taxPercent": {
      "type": "number"
    },
    "totalTaxAmount": {
      "type": "number"
    },
    "amountIncludingTax": {
      "type": "number"
    },
    "expectedReceiptDate": {
      "type": "string"
    },
    "receivedQuantity": {
      "type": "number"
    },
    "invoicedQuantity": {
      "type": "number"
    },
    "invoiceQuantity": {
      "type": "number"
    },
    "receiveQuantity": {
      "type": "number"
    }
  }
}

=== api-evangelist/navision/examples/business-central-v2-purchase-order-line-example.json
{
  "@odata.etag": "example_value",
  "id": "abc123",
  "documentId": "500123",
  "sequence": 10,
  "itemId": "500123",
  "accountId": "500123",
  "lineType": "example_value",
  "lineObjectNumber": "example_value",
  "description": "A sample description.",
  "description2": "example_value",
  "unitOfMeasureId": "500123",
  "unitOfMeasureCode": "example_value",
  "quantity": 42.5,
  "directUnitCost": 42.5,
  "discountAmount": 42.5,
  "discountPercent": 42.5,
  "discountAppliedBeforeTax": true,
  "amountExcludingTax": 42.5,
  "taxCode": "example_value",
  "taxPercent": 42.5,
  "totalTaxAmount": 42.5,
  "amountIncludingTax": 42.5,
  "expectedReceiptDate": "example_value",
  "receivedQuantity": 42.5,
  "invoicedQuantity": 42.5,
  "invoiceQuantity": 42.5,
  "receiveQuantity": 42.5
}
