=== api-evangelist/navision/json-schema/business-central-v2-employee-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Employee",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "number": {
      "type": "string"
    },
    "displayName": {
      "type": "string"
    },
    "givenName": {
      "type": "string"
    },
    "middleName": {
      "type": "string"
    },
    "surname": {
      "type": "string"
    },
    "jobTitle": {
      "type": "string"
    },
    "addressLine1": {
      "type": "string"
    },
    "addressLine2": {
      "type": "string"
    },
    "city": {
      "type": "string"
    },
    "state": {
      "type": "string"
    },
    "country": {
      "type": "string"
    },
    "postalCode": {
      "type": "string"
    },
    "phoneNumber": {
      "type": "string"
    },
    "mobilePhone": {
      "type": "string"
    },
    "email": {
      "type": "string"
    },
    "personalEmail": {
      "type": "string"
    },
    "employmentDate": {
      "type": "string"
    },
    "terminationDate": {
      "type": "string"
    },
    "status": {
      "type": "string"
    },
    "birthDate": {
      "type": "string"
    },
    "statisticsGroupCode": {
      "type": "string"
    },
    "lastModifiedDateTime": {
      "type": "string"
    }
  }
}

=== api-evangelist/navision/examples/business-central-v2-employee-example.json
{
  "id": "abc123",
  "number": "example_value",
  "displayName": "example_value",
  "givenName": "example_value",
  "middleName": "example_value",
  "surname": "example_value",
  "jobTitle": "example_value",
  "addressLine1": "example_value",
  "addressLine2": "example_value",
  "city": "example_value",
  "state": "example_value",
  "country": "example_value",
  "postalCode": "example_value",
  "phoneNumber": "example_value",
  "mobilePhone": "example_value",
  "email": "user@example.com",
  "personalEmail": "user@example.com",
  "employmentDate": "example_value",
  "terminationDate": "example_value",
  "status": "example_value",
  "birthDate": "example_value",
  "statisticsGroupCode": "example_value",
  "lastModifiedDateTime": "example_value"
}
