=== api-evangelist/navision/json-schema/business-central-v2-vendor-create-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "VendorCreate",
  "type": "object",
  "properties": {
    "number": {
      "type": "string"
    },
    "displayName": {
      "type": "string"
    },
    "addressLine1": {
      "type": "string"
    },
    "addressLine2": {
      "type": "string"
    },
    "city": {
      "type": "string"
    },
    "state": {
      "type": "string"
    },
    "country": {
      "type": "string"
    },
    "postalCode": {
      "type": "string"
    },
    "phoneNumber": {
      "type": "string"
    },
    "email": {
      "type": "string"
    },
    "website": {
      "type": "string"
    },
    "taxRegistrationNumber": {
      "type": "string"
    },
    "currencyCode": {
      "type": "string"
    },
    "taxLiable": {
      "type": "boolean"
    },
    "blocked": {
      "type": "string"
    }
  }
}

=== api-evangelist/navision/examples/business-central-v2-vendor-create-example.json
{
  "number": "example_value",
  "displayName": "example_value",
  "addressLine1": "example_value",
  "addressLine2": "example_value",
  "city": "example_value",
  "state": "example_value",
  "country": "example_value",
  "postalCode": "example_value",
  "phoneNumber": "example_value",
  "email": "user@example.com",
  "website": "example_value",
  "taxRegistrationNumber": "example_value",
  "currencyCode": "example_value",
  "taxLiable": true,
  "blocked": "example_value"
}
